version: '2'
services:
  web:
    build: .
    command: /bin/true
    volumes:
      - .:/data
    depends_on:
     - mysql
  mysql:
    image: sameersbn/mysql
    hostname: mysql
    volumes:
     - mysql-data:/var/lib/mysql:rw
    environment:
     - DB_NAME=test
     - DB_USER=test
     - DB_PASS=1234
     - DB_REMOTE_ROOT_NAME=root
     - DB_REMOTE_ROOT_PASS=
  pma:
    image: corbinu/docker-phpmyadmin
    hostname: phpmyadmin
    depends_on:
     - mysql
    environment:
     - MYSQL_USERNAME=root
     - MYSQL_PORT_3306_TCP_ADDR=mysql
     - MYSQL_PORT_3306_TCP_PORT=3306
volumes:
  mysql-data:
networks:
  dbal:
    driver: bridge
