<?php

namespace App\Http\Requests;

use App\Models\Product;

class ProductRequest extends FormRequest
{
    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'title' => [
                'required',
                'min:3',
                function ($attribute,$value,$fail){
                if ($product = Product::where("title",$value)->first()){
                    return $fail("标题重复");
                }
            }],
        ];
    }

    public function messages()
    {
//        return parent::messages(); // TODO: Change the autogenerated stub
        return [
            'title.required' => "没有输入标题"
        ];
    }
}
